name: C++ Build

on:
  push:
    branches:
      - main  # Запускается при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускается при создании PR для main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем Ubuntu как операционную систему

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Клонируем код из репозитория

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Compile C++ code
        run: g++ -o main main.cpp

      - name: Run compiled program
        run: ./main
